### ISSUE TITLE
default_transformer_optim_log_fn cannot handle LossDict

### ISSUE THREAD

**Issue by jbueltemeier** [pmeier/pystiche#143]
The `default_transformer_optim_log_fn` cannot handle a `LossDict`. The example below leads to a `KeyError: -1`. 

```python
import torch
from pystiche.optim.log import (
    OptimLogger,
    default_transformer_optim_log_fn
)
from pystiche.core._base import LossDict

log_fn = default_transformer_optim_log_fn(OptimLogger(), 1)
loss = LossDict([("loss", torch.Tensor())])
log_fn(1, loss, 1, 1)
```

**Comment by pmeier** [comment]
This is not a bug right now, since the `update` method `AverageMeter` which is called within `log_fn` has the following signature:

https://github.com/pmeier/pystiche/blob/2f47ea8d14b54704966d7772736d3fee33db6e0c/pystiche/optim/meter.py#L113-L115

You can fix that by calling the `.item()` method on the `LossDict` before passing it to `log_fn`.

---

That said, I agree that we should add this as a new feature.
