### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Barbarosse** [pmeier/pystiche#331]
I am unable to work with larger image size. Even a 1000px output size will results in a "CUDA out of memory" error.
I have a Nvidia 970 gtx with 4GB of ram. 
Thanks.

**Comment by pmeier** [comment]
1000 pixels is quite large for an NST as the [memory requirement grows quadratic with the size](https://github.com/pmeier/pystiche/issues/244#issuecomment-629846251). `pystiche` does not use a lot of overhead and as such this is simply a limitation I can't do anything about.

In the mean time here is what you can do about it:
1. Get a GPU with more memory. If you do, make sure that the memory is accessible from a single GPU. For NST 4x GPU with 4GB of memory is worse than 1x GPU with 8 GB of memory.
2. Perform the NST on a smaller resolution and perform some kind of super-resolution afterwards. This can also be done with [DL algorithms](https://medium.com/beyondminds/an-introduction-to-super-resolution-using-deep-learning-f60aff9a499d).
3. Switch to an optimizer with a lower memory requirement such as [`Adam`](https://pytorch.org/docs/stable/optim.html?highlight=adam#torch.optim.Adam). By default, the examples use [`LBFGS`](https://pystiche.readthedocs.io/en/latest/api/pystiche.optim.html#pystiche.optim.default_image_optimizer) which is the de facto standard optimizer in the research papers. It gives the best results but is also quite memory intensive. You can use every other optimizer like this in the optimization loop:
    ```python
    from torch import optim

    def get_optimizer(input_image):
        return optim.Adam([input_image.requires_grad_(True)], lr=1e-3)

    output_image = default_image_optim_loop(
        input_image, criterion, get_optimizer=get_optimizer
    )
    ```
    Be aware that you most likely need to fiddle with the learning rate (`lr`) as well as `score_weight`s of the content and style loss.
4. Instead of image optimization you can do model optimization. I wrote about the differences [here](https://pystiche.readthedocs.io/en/latest/optim.html). Currently we have no example for model optimization, but you could have a look [here](https://github.com/pmeier/pystiche_papers/blob/master/replication/johnson_alahi_li_2016/main.py), which is the reference implementation of the paper that introduced this concept.

**Comment by Barbarosse** [comment]
Thanks a lot. I tried with other codes, written both for Tensorflow and Pytorch, I've got the same result. 
I tried this [colab](https://colab.research.google.com/github/titu1994/Neural-Style-Transfer/blob/master/NeuralStyleTransfer.ipynb#scrollTo=TLwCzYQyawvJ) code with 16gb of gpu ram and didn't succeed.
