### ISSUE TITLE
the demo is running quiet slowly

### ISSUE THREAD

**Issue by duwangthefirst** [pmeier/pystiche#480]
It takes about more than one minute to produce result even after I change `num_steps` to 10.
```
I'm working with pystiche==0.7.0
I'm working with cpu
```
I'm wondering if there is any real-time style transfer framework for CPU or embedding system.

**Comment by zichuan-scott-xu** [comment]
I have the same problem, also with `pystiche==0.7.0` and cpu.

**Comment by pmeier** [comment]
Hey @duwangthefirst, hey @zichuan-scott-xu. The problem you are facing is expected if you have no GPU, since an image-based style transfer is essentially the same as training a neural network for some steps. If you don't have access to a GPU, the only things you can do about that is to either

- decrease the image size or
- use a "lighter" multi-layer encoder.

Both will of course have an effect on the perceptual quality of the results.

---

Other than that, you could try to use a model-based approach as explained in this [usage example](https://pystiche.readthedocs.io/en/stable/galleries/examples/advanced/example_model_optimization.html#sphx-glr-galleries-examples-advanced-example-model-optimization-py). This shifts the heavy lifting to a training phase and afterwards the stylization can be performed wit ha single forward pass through the transfer net. Of course the training of this transformer net is even more dependent on a GPU compared to the image-based approach.

As of now, I only have a pretrained transformer for the same style that is used in the other demos. When https://github.com/pytorch/examples/issues/837 is resolved I'm hoping to port other styles.

There are papers out there that enable an arbitrary style transfer in real time, but I had no time yet to implement them. For a good overview of what is possible, I suggest you take a look at [this repository](https://github.com/ycjing/Neural-Style-Transfer-Papers). If you implement one of these techniques and want to contribute a usage example, feel free to open an issue.

---

I'm going to close this issue since it is not actionable. For general usage questions, I'd like to try the new ["Discussions" feature](https://github.com/pmeier/pystiche/discussions) GitHub.
